/**
 * ActionSchema.js
 * Definitions for Grok Recorder Missions and Actions
 */

export const SCENARIOS = {
    imagine_gen_with_video__video_gen: {
        id: 'imagine_gen_with_video__video_gen',
        title: 'Image (Gen+Video) -> Make Video',
        description: 'Context: Image generated by AI, Video already exists. Goal: Gen another video.',
        steps: [
            { instruct: 'Navigate to an Imagine-generated post that ALREADY has a video.' },
            { instruct: 'Reset to initial state (Image view).', noCapture: true },
            { instruct: 'Click "Settings" (Gear icon) or "More Options" (...) to open menu.' },
            { instruct: 'Click "Make Video" from the menu.' },
            { instruct: 'Verify the TipTap input (Video Prompt) is visible.', noCapture: true },
            { instruct: 'Type a test prompt (do not submit yet) to verify input focus.', noCapture: true },
            { instruct: 'Click the Submit/Make Video button (Up Arrow).' }
        ]
    },
    imagine_gen_with_video__image_edit: {
        id: 'imagine_gen_with_video__image_edit',
        title: 'Image (Gen+Video) -> Image Edit',
        description: 'Context: Image generated by AI, Video exists. Goal: Edit the image.',
        steps: [
            { instruct: 'Navigate to an Imagine-generated post that ALREADY has a video.' },
            { instruct: 'Reset to initial state (Image view).', noCapture: true },
            { instruct: 'Click "Settings" (Gear) or "More Options" (...).' },
            { instruct: 'Click "Edit Image" from the menu.' },
            { instruct: 'Select a thumbnail (if carousel appears) or verify Edit Mode.' },
            { instruct: 'Click the Submit/Edit button.' }
        ]
    },
    // ... Additional scenarios will be populated here
    uploaded_with_video__video_gen: {
        id: 'uploaded_with_video__video_gen',
        title: 'Upload (Video) -> Make Video',
        description: 'Context: User uploaded image, Video exists. Goal: Gen another.',
        steps: [
            { instruct: 'Navigate to a User-Uploaded post that ALREADY has a video.' },
            { instruct: 'Open the "Make Video" menu/modal.' },
            { instruct: 'Submit a video generation.' }
        ]
    },
    uploaded_with_video__image_edit: {
        id: 'uploaded_with_video__image_edit',
        title: 'Upload (Video) -> Image Edit',
        description: 'Context: User uploaded image, Video exists. Goal: Edit image.',
        steps: [
            { instruct: 'Navigate to a User-Uploaded post that ALREADY has a video.' },
            { instruct: 'Enter Image Edit mode.' },
            { instruct: 'Submit an edit.' }
        ]
    },
    imagine_gen_no_video__video_gen: {
        id: 'imagine_gen_no_video__video_gen',
        title: 'Image (No Video) -> Make Video',
        description: 'Context: Fresh AI image, NO video yet. Goal: First video.',
        steps: [
            { instruct: 'Navigate to a fresh Imagine post (Image ONLY, No Video).' },
            { instruct: 'Find and click "Make Video" (might be in Settings or direct button).' },
            { instruct: 'Submit generation.' }
        ]
    },
    imagine_gen_no_video__image_edit: {
        id: 'imagine_gen_no_video__image_edit',
        title: 'Image (No Video) -> Image Edit',
        description: 'Context: Fresh AI image, No video. Goal: Edit image.',
        steps: [
            { instruct: 'Navigate to a fresh Imagine post.' },
            { instruct: 'Enter Edit Image mode.' },
            { instruct: 'Submit edit.' }
        ]
    },
    uploaded_no_video__video_gen: {
        id: 'uploaded_no_video__video_gen',
        title: 'Upload (No Video) -> Make Video',
        description: 'Context: Fresh Upload, No video. Goal: First video.',
        steps: [
            { instruct: 'Navigate to a fresh User Upload.' },
            { instruct: 'Locate "Make Video" option.' },
            { instruct: 'Submit generation.' }
        ]
    },
    uploaded_no_video__image_edit: {
        id: 'uploaded_no_video__image_edit',
        title: 'Upload (No Video) -> Image Edit',
        description: 'Context: Fresh Upload. Goal: Edit image.',
        steps: [
            { instruct: 'Navigate to a fresh User Upload.' },
            { instruct: 'Enter Edit Image mode.' },
            { instruct: 'Submit edit.' }
        ]
    },
    image_with_edits__carousel_browse: {
        id: 'image_with_edits__carousel_browse',
        title: 'Carousel Navigation',
        description: 'Context: Image with multiple edits. Goal: Browse thumbnails.',
        steps: [
            { instruct: 'Navigate to an image with multiple edit history items.' },
            { instruct: 'Enter Edit Mode to see the thumbnail strip.' },
            { instruct: 'Click Thumbnail 1 (Original).' },
            { instruct: 'Click Thumbnail 2.' },
            { instruct: 'Click Thumbnail 3 (if exists).' }
        ]
    }
};

export const ACTIONS = {
    START: 'START',
    NEXT: 'NEXT',
    RETRY: 'RETRY',
    STOP: 'STOP',
    CAPTURE: 'CAPTURE'
};
